server :
  port : 8083
  servlet :
    context-path : /demo
  tomcat :
    uri-encoding : UTF-8

#配置文件
com :
  neo :
    title : "测试title"
    description : "sdasd"

#日志输出
logging :
  path : /user/local/log
  level :
    com :
      example : DEBUG

#mysql配置
spring :
  datasource :
    url : jdbc:mysql://localhost:3306/demo_test
    username : root
    password : root
    driver-class-name : com.mysql.jdbc.Driver
  jpa :
    properties :
      hibernate :
        hbm2ddl :
          auto : update
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql : true